"""
Resume Templates Feature — Implementation Plan (PDF)
Career Pilot / resume-builder enhancement
"""
import os
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm, inch, mm
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, HRFlowable,
    Table, TableStyle, KeepTogether, PageBreak,
)
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily

# ━━ Color Palette (auto-generated by pdf.py palette.generate) ━━
# Intent: neutral | Mode: minimal | Harmony: split_complementary
ACCENT        = colors.HexColor('#187999')
TEXT_PRIMARY  = colors.HexColor('#181a1b')
TEXT_MUTED    = colors.HexColor('#7a8287')
BG_SURFACE    = colors.HexColor('#dbe1e4')
BG_PAGE       = colors.HexColor('#f1f3f4')

# ━━ Font Registration ━━
pdfmetrics.registerFont(TTFont('TimesNewRoman',
    '/System/Library/Fonts/Supplemental/Times New Roman.ttf'))
pdfmetrics.registerFont(TTFont('TimesNewRomanBold',
    '/System/Library/Fonts/Supplemental/Times New Roman Bold.ttf'))
pdfmetrics.registerFont(TTFont('Menlo',
    '/System/Library/Fonts/Menlo.ttc', subfontIndex=0))
registerFontFamily('TimesNewRoman',
    normal='TimesNewRoman', bold='TimesNewRomanBold')
registerFontFamily('Menlo', normal='Menlo', bold='Menlo')

# ━━ Styles ━━
title_style = ParagraphStyle(
    'PlanTitle', fontName='TimesNewRomanBold', fontSize=28,
    leading=34, alignment=TA_LEFT, textColor=TEXT_PRIMARY,
    spaceAfter=4,
)
subtitle_style = ParagraphStyle(
    'PlanSubtitle', fontName='TimesNewRoman', fontSize=13,
    leading=18, alignment=TA_LEFT, textColor=TEXT_MUTED,
    spaceAfter=20,
)
h1_style = ParagraphStyle(
    'H1', fontName='TimesNewRomanBold', fontSize=16,
    leading=22, textColor=ACCENT, spaceBefore=18, spaceAfter=6,
)
h2_style = ParagraphStyle(
    'H2', fontName='TimesNewRomanBold', fontSize=13,
    leading=18, textColor=TEXT_PRIMARY, spaceBefore=14, spaceAfter=4,
)
body_style = ParagraphStyle(
    'Body', fontName='TimesNewRoman', fontSize=10.5,
    leading=16, alignment=TA_JUSTIFY, spaceAfter=4,
)
bullet_style = ParagraphStyle(
    'Bullet', fontName='TimesNewRoman', fontSize=10.5,
    leading=16, leftIndent=18, bulletIndent=4,
    spaceBefore=1, spaceAfter=1,
)
code_style = ParagraphStyle(
    'Code', fontName='Menlo', fontSize=8.5,
    leading=13, leftIndent=12, textColor=colors.HexColor('#3b4045'),
    backColor=colors.HexColor('#f6f8fa'),
    spaceBefore=2, spaceAfter=2,
    borderPadding=(6, 8, 4, 8),
)
caption_style = ParagraphStyle(
    'Caption', fontName='TimesNewRoman', fontSize=9,
    leading=13, alignment=TA_CENTER, textColor=TEXT_MUTED,
    spaceBefore=2, spaceAfter=8,
)
header_cell = ParagraphStyle(
    'HeaderCell', fontName='TimesNewRomanBold', fontSize=10,
    textColor=colors.white, alignment=TA_CENTER,
)
cell_style = ParagraphStyle(
    'Cell', fontName='TimesNewRoman', fontSize=10,
    leading=14,
)
callout_style = ParagraphStyle(
    'Callout', fontName='TimesNewRoman', fontSize=10,
    leading=15, leftIndent=14, textColor=TEXT_PRIMARY,
    borderPadding=(8, 8, 6, 8),
    backColor=colors.HexColor('#eef5f8'),
)

# ━━ Helpers ━━
def section(title, style=h1_style):
    return [Paragraph(f'<b>{title}</b>', style),
            HRFlowable(width='100%', thickness=0.8, color=ACCENT,
                       spaceBefore=0, spaceAfter=8)]

def bullets(items):
    return [Paragraph(f'• {item}', bullet_style) for item in items]

def code_block(text):
    return Paragraph(text, code_style)

def note(text):
    return Paragraph(text, callout_style)

# ━━ Build Document ━━
OUTPUT = os.path.join(os.path.dirname(__file__), 'Resume_Templates_Implementation_Plan.pdf')

doc = SimpleDocTemplate(
    OUTPUT, pagesize=A4,
    leftMargin=2.0*cm, rightMargin=2.0*cm,
    topMargin=2.0*cm, bottomMargin=2.0*cm,
    title='Resume Templates Feature - Implementation Plan',
    author='Career Pilot', creator='Z.ai',
    subject='5 professional resume templates with AI-parsed data and PDF export',
)

story = []

# ── Cover ──
story.append(Spacer(1, 120))
story.append(Paragraph('<b>Resume Templates Feature</b>', title_style))
story.append(Paragraph('<b>Implementation Plan</b>', ParagraphStyle(
    'Sub2', fontName='TimesNewRomanBold', fontSize=18,
    leading=24, textColor=TEXT_PRIMARY, spaceAfter=6)))
story.append(HRFlowable(width='40%', thickness=2, color=ACCENT,
                          spaceBefore=6, spaceAfter=12))
story.append(Paragraph('Career Pilot  |  resume-builder enhancement', subtitle_style))
story.append(Paragraph('June 2026', ParagraphStyle(
    'Date', fontName='TimesNewRoman', fontSize=11,
    leading=14, textColor=TEXT_MUTED)))
story.append(Spacer(1, 40))
story.append(Paragraph(
    'Add 5 professional resume templates that consume the app\'s structured '
    '"parse AI data" shape, render live from the user\'s data, and export to '
    'multi-page A4 PDF. Pure frontend feature, no backend changes required.',
    body_style))
story.append(PageBreak())

# ── 1. Goal ──
story.extend(section('1. Goal'))
story.append(Paragraph(
    'Add <b>5 professional resume templates</b> that consume the structured '
    '"parse AI data" shape already produced by the app\'s AI extractor and '
    'ResumeBuilder wizard. Users select a template on a new gallery page, see '
    'a live preview populated with their own data, and export to <b>multi-page '
    'A4 PDF</b> via client-side html2canvas + jspdf (both already installed '
    'in package.json).',
    body_style))

# ── 2. Architecture Overview ──
story.extend(section('2. Architecture Overview'))
story.append(Paragraph(
    'Reuse the <b>proven portfolio template-system pattern</b> already '
    'established in the codebase (registry + per-template folder + context '
    'provider + dynamic lazy import), but scoped to a new ResumeContext that '
    'produces a resume-optimized data shape. This avoids polluting the '
    'portfolio system and lets templates read fields a resume needs '
    '(education, split contact info, bullet-split experience) that the AI '
    'extractor does not currently emit.',
    body_style))

story.append(Spacer(1, 6))
story.append(code_block(
    'Data Flow<br/>'
    'ResumeBuilder form  --+<br/>'
    'Saved resume (text)  --+--> normalizeResumeData() --> ResumeProvider --> <Template/><br/>'
    'localStorage draft   --+            (resume-shaped)        useResume()<br/>'
    '                                                              |<br/>'
    '                                                 html2canvas + jspdf --> PDF'))

story.append(Spacer(1, 4))
story.append(Paragraph(
    '<b>normalizeResumeData()</b> merges from three sources in priority order, '
    'against a dummy_resume.json fallback:',
    body_style))
story.extend(bullets([
    '<b>AI-extracted draft</b> (localStorage ai_resume_draft / ai_portfolio_draft) - already structured JSON',
    '<b>ResumeBuilder form state</b> - passed via location.state when navigating from the builder\'s preview step',
    '<b>Saved resume</b> - fetched via resumeApi.getById(); its enhancedText/originalText markdown lightly split into sections client-side',
]))

# ── 3. Data Contract ──
story.extend(section('3. Canonical Resume Data Shape'))
story.append(Paragraph(
    'All 5 templates read from this unified shape via the '
    '<font name="Menlo">useResume()</font> hook. Field aliases are handled '
    'inside normalizeResumeData() so templates only need to read the canonical keys.',
    body_style))

data_table_data = [
    [Paragraph('<b>Section</b>', header_cell),
     Paragraph('<b>Fields</b>', header_cell),
     Paragraph('<b>Type</b>', header_cell)],
    [Paragraph('personal', cell_style),
     Paragraph('name, title, summary, email, phone, location, website, linkedin, github', cell_style),
     Paragraph('object', cell_style)],
    [Paragraph('experience', cell_style),
     Paragraph('{ role, company, period, location, bullets[] }', cell_style),
     Paragraph('array', cell_style)],
    [Paragraph('education', cell_style),
     Paragraph('{ degree, institution, period, location, description }', cell_style),
     Paragraph('array', cell_style)],
    [Paragraph('projects', cell_style),
     Paragraph('{ title, description, techStack[], link }', cell_style),
     Paragraph('array', cell_style)],
    [Paragraph('skills', cell_style),
     Paragraph('{ name, level, category }', cell_style),
     Paragraph('array', cell_style)],
    [Paragraph('certifications', cell_style),
     Paragraph('{ name, issuer, year }', cell_style),
     Paragraph('array', cell_style)],
]
avail_w = A4[0] - 4.0*cm
dt = Table(data_table_data, colWidths=[avail_w*0.16, avail_w*0.62, avail_w*0.22],
           hAlign='CENTER')
dt.setStyle(TableStyle([
    ('BACKGROUND', (0,0), (-1,0), ACCENT),
    ('TEXTCOLOR', (0,0), (-1,0), colors.white),
    ('BACKGROUND', (0,1), (-1,1), colors.white),
    ('BACKGROUND', (0,2), (-1,2), BG_SURFACE),
    ('BACKGROUND', (0,3), (-1,3), colors.white),
    ('BACKGROUND', (0,4), (-1,4), BG_SURFACE),
    ('BACKGROUND', (0,5), (-1,5), colors.white),
    ('BACKGROUND', (0,6), (-1,6), BG_SURFACE),
    ('GRID', (0,0), (-1,-1), 0.5, TEXT_MUTED),
    ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
    ('LEFTPADDING', (0,0), (-1,-1), 8),
    ('RIGHTPADDING', (0,0), (-1,-1), 8),
    ('TOPPADDING', (0,0), (-1,-1), 5),
    ('BOTTOMPADDING', (0,0), (-1,-1), 5),
]))
story.append(Spacer(1, 8))
story.append(dt)
story.append(Paragraph('Table 1: Canonical resume data shape (template contract)', caption_style))

# ── 4. Files to Create ──
story.extend(section('4. Files to Create'))

story.append(Paragraph('<b>4.1 Data Layer</b>', h2_style))
story.extend(bullets([
    '<font name="Menlo">frontend/src/data/dummy_resume.json</font> - resume-shaped seed/fallback (personal, contact, summary, experience[], education[], projects[], skills[], certifications[])',
    '<font name="Menlo">frontend/src/data/resumeTemplates.js</font> - registry array mirroring templates.js: [{ id, name, category:"Resume", description, accent, layout, thumb }] (5 entries)',
    '<font name="Menlo">frontend/src/context/ResumeContext.jsx</font> - normalizeResumeData(raw) + ResumeProvider + useResume() hook. Mirrors PortfolioContext.jsx pattern. Handles string-skill coercion, project alias mapping (title||name, techStack||technologies), experience alias (role||title, period||startDate-endDate), splits multi-line descriptions into bullet arrays.',
]))

story.append(Paragraph('<b>4.2 Template Components</b>', h2_style))
story.append(Paragraph(
    'Each template lives at <font name="Menlo">frontend/src/components/resume/templates/<ID>/index.jsx</font>, '
    'default-exports a component reading <font name="Menlo">useResume()</font>, '
    'and uses defensive field reads (e.g., <font name="Menlo">exp?.role || exp?.title</font>). '
    'Root div carries class <font name="Menlo">resume-export-root</font> for PDF export targeting. '
    'Templates render at A4 width (210mm) with print-safe colors and no fixed heights (multi-page friendly).',
    body_style))

template_table = [
    [Paragraph('<b>#</b>', header_cell),
     Paragraph('<b>Template ID</b>', header_cell),
     Paragraph('<b>Layout</b>', header_cell),
     Paragraph('<b>Style</b>', header_cell),
     Paragraph('<b>Best For</b>', header_cell)],
    [Paragraph('1', cell_style), Paragraph('ModernSidebar', cell_style),
     Paragraph('Two-column', cell_style), Paragraph('Accent sidebar', cell_style),
     Paragraph('Tech, general', cell_style)],
    [Paragraph('2', cell_style), Paragraph('ClassicSerif', cell_style),
     Paragraph('Single-column', cell_style), Paragraph('Georgia serif', cell_style),
     Paragraph('Corporate, ATS', cell_style)],
    [Paragraph('3', cell_style), Paragraph('MinimalSans', cell_style),
     Paragraph('Single-column', cell_style), Paragraph('Clean whitespace', cell_style),
     Paragraph('Startups, modern', cell_style)],
    [Paragraph('4', cell_style), Paragraph('CompactTwoCol', cell_style),
     Paragraph('Two-column', cell_style), Paragraph('Dense, icon-led', cell_style),
     Paragraph('Experienced devs', cell_style)],
    [Paragraph('5', cell_style), Paragraph('ExecutiveBand', cell_style),
     Paragraph('Single-column', cell_style), Paragraph('Header band', cell_style),
     Paragraph('Senior, executive', cell_style)],
]
tt = Table(template_table, colWidths=[avail_w*0.06, avail_w*0.22, avail_w*0.2, avail_w*0.22, avail_w*0.3],
           hAlign='CENTER')
tt.setStyle(TableStyle([
    ('BACKGROUND', (0,0), (-1,0), ACCENT),
    ('TEXTCOLOR', (0,0), (-1,0), colors.white),
    ('BACKGROUND', (0,1), (-1,1), colors.white),
    ('BACKGROUND', (0,2), (-1,2), BG_SURFACE),
    ('BACKGROUND', (0,3), (-1,3), colors.white),
    ('BACKGROUND', (0,4), (-1,4), BG_SURFACE),
    ('BACKGROUND', (0,5), (-1,5), colors.white),
    ('GRID', (0,0), (-1,-1), 0.5, TEXT_MUTED),
    ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
    ('LEFTPADDING', (0,0), (-1,-1), 6),
    ('RIGHTPADDING', (0,0), (-1,-1), 6),
    ('TOPPADDING', (0,0), (-1,-1), 5),
    ('BOTTOMPADDING', (0,0), (-1,-1), 5),
]))
story.append(Spacer(1, 8))
story.append(tt)
story.append(Paragraph('Table 2: Five resume template designs', caption_style))

story.append(Paragraph('<b>4.3 Gallery Page</b>', h2_style))
story.extend(bullets([
    '<font name="Menlo">frontend/src/pages/ResumeTemplates.jsx</font> - the new gallery page with live preview + PDF export. Loads data from location.state (builder), resumeId query param, or localStorage draft. Shows 5 template cards, on select switches to full-width live preview with a "Download PDF" button.',
]))

# ── 5. Files to Modify ──
story.extend(section('5. Files to Modify'))

mod_table = [
    [Paragraph('<b>File</b>', header_cell),
     Paragraph('<b>Change</b>', header_cell),
     Paragraph('<b>Impact</b>', header_cell)],
    [Paragraph('frontend/src/App.jsx', cell_style),
     Paragraph('Lazy-import ResumeTemplates, register route /resume-templates under ProtectedRoute + Suspense', cell_style),
     Paragraph('Routing only', cell_style)],
    [Paragraph('frontend/src/pages/ResumeBuilder.jsx', cell_style),
     Paragraph('Add "Choose Resume Template" button on the preview step that navigates to /resume-templates with { state: { builderData } }', cell_style),
     Paragraph('One button', cell_style)],
    [Paragraph('frontend/src/pages/ResumeView.jsx', cell_style),
     Paragraph('Add "Templates" button in the header action row (next to Enhance) navigating to /resume-templates?resumeId={id}', cell_style),
     Paragraph('One button', cell_style)],
]
mt = Table(mod_table, colWidths=[avail_w*0.30, avail_w*0.48, avail_w*0.22],
           hAlign='CENTER')
mt.setStyle(TableStyle([
    ('BACKGROUND', (0,0), (-1,0), ACCENT),
    ('TEXTCOLOR', (0,0), (-1,0), colors.white),
    ('BACKGROUND', (0,1), (-1,1), colors.white),
    ('BACKGROUND', (0,2), (-1,2), BG_SURFACE),
    ('BACKGROUND', (0,3), (-1,3), colors.white),
    ('GRID', (0,0), (-1,-1), 0.5, TEXT_MUTED),
    ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
    ('LEFTPADDING', (0,0), (-1,-1), 8),
    ('RIGHTPADDING', (0,0), (-1,-1), 8),
    ('TOPPADDING', (0,0), (-1,-1), 5),
    ('BOTTOMPADDING', (0,0), (-1,-1), 5),
]))
story.append(Spacer(1, 8))
story.append(mt)
story.append(Paragraph('Table 3: Files to modify', caption_style))

# ── 6. PDF Export Implementation ──
story.extend(section('6. PDF Export Implementation'))
story.append(Paragraph(
    'Client-side in ResumeTemplates.jsx, a <font name="Menlo">handleDownloadPdf()</font> helper '
    'reuses the already-installed <font name="Menlo">html2canvas</font> and <font name="Menlo">jspdf</font> packages:',
    body_style))

story.extend(bullets([
    '<font name="Menlo">html2canvas(rootNode, { scale: 2, useCORS: true, backgroundColor: \'#fff\' })</font> - renders the selected template DOM at 2x resolution',
    'Compute A4 aspect ratio; slice the tall canvas into page-height chunks',
    '<font name="Menlo">new jsPDF(\'p\', \'mm\', \'a4\')</font> - for each chunk, <font name="Menlo">addImage()</font>, <font name="Menlo">addPage()</font> for subsequent pages',
    '<font name="Menlo">doc.save(\`${name}_resume.pdf\`)</font> - triggers browser download',
    'Toast feedback with loading state on the download button',
]))
story.append(Spacer(1, 4))
story.append(note(
    '<b>Why client-side PDF?</b> The existing ResumeView uses a server-side PDF endpoint, '
    'but it only renders markdown text - not styled React templates. Client-side html2canvas + '
    'jspdf captures the exact visual output of any template without server changes. '
    'Both libraries are already in package.json (jspdf currently unused).'))

# ── 7. Implementation Order ──
story.extend(section('7. Implementation Order'))

steps = [
    ('Step 1', 'dummy_resume.json + ResumeContext.jsx', 'Data foundation - context + normalization'),
    ('Step 2', 'resumeTemplates.js registry', '5-entry metadata array'),
    ('Step 3', 'Five template components', 'ModernSidebar, ClassicSerif, MinimalSans, CompactTwoCol, ExecutiveBand'),
    ('Step 4', 'ResumeTemplates.jsx page', 'Gallery + live preview + PDF export handler'),
    ('Step 5', 'App.jsx route + entry buttons', 'Wire routing and navigation from ResumeBuilder/ResumeView'),
    ('Step 6', 'Build + lint verification', 'npm run build, npx eslint - zero errors'),
]
step_data = [[Paragraph('<b>Step</b>', header_cell),
             Paragraph('<b>Deliverable</b>', header_cell),
             Paragraph('<b>Notes</b>', header_cell)]]
for i, (step, deliverable, notes) in enumerate(steps):
    step_data.append([Paragraph(step, cell_style),
                      Paragraph(deliverable, cell_style),
                      Paragraph(notes, cell_style)])

st = Table(step_data, colWidths=[avail_w*0.14, avail_w*0.42, avail_w*0.44],
           hAlign='CENTER')
st_styles = [
    ('BACKGROUND', (0,0), (-1,0), ACCENT),
    ('TEXTCOLOR', (0,0), (-1,0), colors.white),
    ('GRID', (0,0), (-1,-1), 0.5, TEXT_MUTED),
    ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
    ('LEFTPADDING', (0,0), (-1,-1), 8),
    ('RIGHTPADDING', (0,0), (-1,-1), 8),
    ('TOPPADDING', (0,0), (-1,-1), 5),
    ('BOTTOMPADDING', (0,0), (-1,-1), 5),
]
for i in range(1, len(step_data)):
    bg = colors.white if i % 2 == 1 else BG_SURFACE
    st_styles.append(('BACKGROUND', (0,i), (-1,i), bg))
st.setStyle(TableStyle(st_styles))
story.append(Spacer(1, 8))
story.append(st)
story.append(Paragraph('Table 4: Implementation sequence', caption_style))

# ── 8. Verification ──
story.extend(section('8. Verification'))
story.extend(bullets([
    '<font name="Menlo">npm run build</font> - confirms all 5 templates + new page compile with no syntax/import errors',
    '<font name="Menlo">npx eslint</font> on new files - zero errors (warnings acceptable)',
    'Manual smoke test: navigate from ResumeBuilder to /resume-templates, cycle each template, download PDF and verify multi-page output',
]))

# ── 9. Out of Scope ──
story.extend(section('9. Out of Scope'))
story.extend(bullets([
    'No backend changes - all data already exists client-side via AI extractor and ResumeBuilder',
    'No deploy-to-hosting - that is the portfolio system\'s responsibility',
    'No ATS re-scoring of the rendered template output',
    'No inline template style editor - templates use their designed layout as-is',
    'No new npm dependencies - html2canvas and jspdf already in package.json',
]))

# ── 10. Key Design Decisions ──
story.extend(section('10. Key Design Decisions'))

story.append(Paragraph('<b>10.1 Separate ResumeContext vs. Reusing PortfolioContext</b>', h2_style))
story.append(Paragraph(
    'A separate context is preferred because: (a) resume templates need fields '
    'the portfolio context doesn\'t normalize (education[], certifications[], '
    'contact phone/email as top-level fields); (b) the portfolio context merges '
    'against portfolio-specific dummy_data.json which has a different shape; '
    '(c) it avoids unintended side effects if the portfolio context changes in '
    'the future. The pattern is identical to PortfolioContext, just scoped to resume data.',
    body_style))

story.append(Paragraph('<b>10.2 Template Storage Location</b>', h2_style))
story.append(Paragraph(
    'Templates go under <font name="Menlo">frontend/src/components/resume/templates/</font> '
    'rather than the existing <font name="Menlo">frontend/src/components/portfolio/templates/</font>. '
    'This keeps concerns separated and lets the TemplateGallery page filter by '
    'the existing "Resume" category (already defined in CATEGORY_OPTIONS but '
    'currently unused) if desired in the future.',
    body_style))

story.append(Paragraph('<b>10.3 Multi-page PDF Strategy</b>', h2_style))
story.append(Paragraph(
    'The client-side html2canvas + jspdf approach slices a single tall canvas '
    'into A4-height chunks. This works reliably because templates use no fixed '
    'heights and flow naturally. An alternative (react-to-print) was considered '
    'but requires users to interact with the browser print dialog, adding friction. '
    'The chosen approach provides a one-click download experience.',
    body_style))

# ── Build ──
doc.build(story)
print(f'PDF generated: {OUTPUT}')
